[package]
cairo-version = "2.2.0"
name = "eternum_guild_module"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[lib]
sierra = false  # Enable Sierra codegen.
casm = false   # Enable CASM codegen.

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" , tag = "v0.3.10"}

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x3ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x300001800000000300000180000000000030000000000003006001800006600"
# world_address = "0x789c94ef39aeebc7f8c4c4633030faefb8bee454e358ae53d06ced36136d7d6"
# keystore_password = "password"
# keystore_path = "../keystore.json"
